export const CAR_MODELS = [
  "Tesla Model S",
  "Tesla Model 3",
  "Tesla Model X",
  "Tesla Model Y",
  "Tesla Roadster",
  "Tesla Cybertruck",
  "Toyota Camry",
  "Toyota Corolla",
  "Toyota Land Cruiser",
  "Toyota Supra",
  "Toyota Avalon",
  "Toyota Yaris",
  "Toyota Prius",
  "Toyota Highlander",
  "Toyota 4Runner",
  "Nissan GT-R",
  "Nissan Skyline",
  "Nissan Silvia",
  "Nissan 370Z",
  "Nissan Leaf",
  "Nissan Altima",
  "Nissan Maxima",
  "Nissan Rogue",
  "Nissan Titan",
  "Mercedes S-Class",
  "Mercedes E-Class",
  "Mercedes C-Class",
  "Mercedes G-Wagon",
  "Mercedes A-Class",
  "Mercedes CLA",
  "Mercedes GLE",
  "Mercedes GLS",
  "Mercedes SL",
  "BMW M5",
  "BMW M3",
  "BMW X6",
  "BMW M8",
  "BMW i8",
  "BMW 7 Series",
  "BMW 4 Series",
  "BMW X5",
  "BMW Z4",
  "Ford Mustang",
  "Ford GT",
  "Ford F-150",
  "Ford Focus RS",
  "Ford Bronco",
  "Ford Fiesta",
  "Ford Explorer",
  "Ford Expedition",
  "Ferrari 488",
  "Ferrari LaFerrari",
  "Ferrari F40",
  "Ferrari 812",
  "Ferrari Roma",
  "Ferrari Portofino",
  "Ferrari SF90",
  "Lamborghini Aventador",
  "Lamborghini Huracan",
  "Lamborghini Urus",
  "Lamborghini Countach",
  "Lamborghini Diablo",
  "Lamborghini Sian",
  "Porsche 911",
  "Porsche Taycan",
  "Porsche Panamera",
  "Porsche Cayenne",
  "Porsche Macan",
  "Porsche Boxster",
  "Porsche Cayman",
  "Audi R8",
  "Audi RS6",
  "Audi RS7",
  "Audi TT",
  "Audi A8",
  "Audi Q8",
  "Audi A5",
  "Audi e-tron",
  "Honda Civic Type R",
  "Honda NSX",
  "Honda S2000",
  "Honda Accord",
  "Honda CR-V",
  "Honda Pilot",
  "Volkswagen Golf GTI",
  "Volkswagen Arteon",
  "Volkswagen Beetle",
  "Volkswagen Passat",
  "Volkswagen Touereag",
  "Bugatti Chiron",
  "Bugatti Veyron",
  "Bugatti Divo",
  "Bugatti Centodieci",
  "Koenigsegg Jesko",
  "Koenigsegg Agera",
  "Koenigsegg Regera",
  "Koenigsegg Gemera",
  "Pagani Huayra",
  "Pagani Zonda",
  "Pagani Utopia",
  "McLaren P1",
  "McLaren 720S",
  "McLaren Senna",
  "McLaren F1",
  "McLaren Artura",
  "Aston Martin DB11",
  "Aston Martin Vantage",
  "Aston Martin DBS",
  "Aston Martin Valkyrie",
  "Mazda RX-7",
  "Mazda MX-5",
  "Mazda RX-8",
  "Mazda CX-5",
  "Subaru WRX STI",
  "Subaru BRZ",
  "Subaru Outback",
  "Mitsubishi Lancer Evo",
  "Mitsubishi Eclipse",
  "Mitsubishi Pajero",
  "Alfa Romeo Giulia",
  "Alfa Romeo 4C",
  "Jaguar F-Type",
  "Jaguar XJ",
  "Lexus LFA",
  "Lexus LS",
  "Volvo XC90",
  "Polestar 2",
];
